clusterDomain: cluster.local
logRetentionBytes: _1073741824
defaultReplicationFactor: 3
offsetsTopicReplicationFactor: 3
transactionStateLogReplicationFactor: 3
numPartitions: 20
replicaCount: 5
sidecars: {}
autoCreateTopicsEnable: true
# CAUTION: Option to delete topics should be disabled in production.
# Env vars: KAFKA_CFG_DELETE_TOPIC_ENABLE=false
deleteTopicEnable: false

persistence:
  enabled: true
  accessModes:
    - ReadWriteOnce
  size: 8Gi

zookeeper:
  replicaCount: 5
  resources:
    limits:
      memory: 256Mi
      cpu: 250m
    requests:
      memory: 256Mi
      cpu: 250m
  persistence:
    enabled: true
    size: 2Gi

resources:
  limits:
    cpu: 200m
    memory: 2Gi
  requests: 
    cpu: 200m
    memory: 2Gi

startupProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 1
  failureThreshold: 30
  successThreshold: 1


rbac:
  create: true
